environment=QA
# API configuration details
userservice.qa.api.base.url=https://qa.elevate-apis.shikshalokam.org/
userservice.login.endpointasuser=user/v1/account/login
userservice.deleteUserEndPoint=user/v1/admin/deleteUser/
userservice.qa.tenantdomain.origin=qa.elevate-shikshalokam.shikshalokam.org
userservice.url=https://qa.elevate-shikshalokam.shikshalokam.org/

# Login Details - System Admin
userservice.qa.admin.login.user=sl-qa@shikshalokam.org
userservice.qa.admin.login.password=PassworD@@@123

# Login Details - Tenant Admin
userservice.qa.tenantadmin.login.user=slmbprogrammanagerdhalai@yopmail.com
userservice.qa.tenantadmin.login.password=Password@1234

# Login Details - Phone Number
userservice.qa.phone.login.identifier=phonenumberlogin
userservice.qa.phone.login.password=PASSword##11
userservice.qa.phone.code=+91

# Login Details - Username
userservice.qa.username.login.identifier=phonenumberlogin
userservice.qa.username.login.password=PASSword##11

# Login Details - Email
userservice.qa.email.login.identifier=allrightsp_xwjxdyzhz9moip
userservice.qa.email.login.password=PASSword@@@123

# Invalid Login Details
userservice.qa.invalid.identifier=invaliduser
userservice.qa.invalid.password=wrongpassword

# Origin
ep.sg.origin=qa.elevate-shikshagraha.shikshalokam.org
ep.sl.origin=qa.elevate-shikshalokam.shikshalokam.org

# User Search API
userservice.search.user.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/account/search?type=ALL&tenant_code=default
userservice.search.user.id=4
userservice.search.user.invalid.id=99999999




# Admin Login Endpoint
userservice.admin.login.endpoint=user/v1/admin/login

# Read User API
userservice.read.user.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/user/read

# Profile By ID API
userservice.profilebyid.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/user/profileById/

# Update User API
userservice.update.user.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/user/update

# Invalid Token
userservice.invalid.x.auth.token=invalidToken123

# User IDs
userservice.user.id=1
userservice.invalid.user.id=999999

# Internal Access Token
userservice.internal.access.token=Fqn0m0HQ0gXydRtBCg5l

# Update User Payload
userservice.update.user.name=Nevil
userservice.update.user.about=backend engineer 1

userservice.update.user.block=67c82d0c538125889163f197
userservice.update.user.state=67c82d0c538125889163f197
userservice.update.user.school=67c82d7abad58c889bc5a627
userservice.update.user.cluster=67c82d7abad58c889bc5a627
userservice.update.user.district=67c82d37bad58c889bc5a5da
userservice.update.user.professional.role=6822fc2d4e2812081f3425d9
userservice.update.user.professional.subrole=68230cdb4e2812081f342807

# Bulk User Upload
userservice.bulkupload.getsignedurl.endpoint=/user/v1/cloud-services/file/getSignedUrl
userservice.bulkupload.create.endpoint=/user/v1/tenant/bulkUserCreate

# CSV Details
userservice.bulkupload.csv.filename=bulk_users_creation.csv
userservice.bulkupload.csv.path=src/main/resources/bulk_users_creation.csv

# Tenant Headers
userservice.bulkupload.tenant.code=shikshalokam
userservice.bulkupload.org.code=sot

# Entity Type APIs

userservice.entitytype.create.endpoint=/user/v1/entity-type/create
userservice.entitytype.read.endpoint=/user/v1/entity-type/read
userservice.entitytype.delete.endpoint=/user/v1/entity-type/delete/

# Entity Type Test Data

userservice.entitytype.value=ln
userservice.entitytype.label=Languages
userservice.entitytype.status=ACTIVE
userservice.entitytype.type=SYSTEM
userservice.entitytype.modelname=User
userservice.entitytype.datatype=STRING