environment=QA
# API configuration details
userservice.qa.api.base.url=https://qa.elevate-apis.shikshalokam.org/
userservice.login.endpointasuser=user/v1/account/login
userservice.admiLoginEndPoint=user/v1/admin/login
userservice.deleteUserEndPoint=user/v1/admin/deleteUser/
userservice.qa.tenantdomain.origin=qa.elevate-shikshalokam.shikshalokam.org
userservice.url=https://qa.elevate-shikshalokam.shikshalokam.org/

# Login Details - Email
userservice.qa.admin.login.user=sl-qa@shikshalokam.org
userservice.qa.admin.login.password=Password@1234

# Login Details - Phone Number
userservice.qa.phone.login.identifier=phonenumberlogin
userservice.qa.phone.login.password=PASSword##11
userservice.qa.phone.code=+91

# Login Details - Username
userservice.qa.username.login.identifier=phonenumberlogin
userservice.qa.username.login.password=PASSword##11

# Login Details - Email
userservice.qa.email.login.identifier=allrightsp_xwjxdyzhz9moip
userservice.qa.email.login.password=PASSword@@@123

# Invalid Login Details
userservice.qa.invalid.identifier=invaliduser
userservice.qa.invalid.password=wrongpassword

# Origin
ep.sg.origin=qa.elevate-shikshagraha.shikshalokam.org
ep.sl.origin=qa.elevate-shikshalokam.shikshalokam.org

# User Search API
userservice.search.user.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/account/search?type=ALL&tenant_code=default
userservice.search.user.id=4
userservice.search.user.invalid.id=99999999