environment=QA
# API configuration details
userservice.qa.api.base.url=https://qa.elevate-apis.shikshalokam.org/
userservice.login.endpointasuser=user/v1/account/login
userservice.admiLoginEndPoint=user/v1/admin/login
userservice.deleteUserEndPoint=user/v1/admin/deleteUser/
userservice.qa.tenantdomain.origin=qa.elevate-shikshalokam.shikshalokam.org
userservice.url=https://qa.elevate-shikshalokam.shikshalokam.org/

# Login Details - Email
userservice.qa.admin.login.user=sl-qa@shikshalokam.org
userservice.qa.admin.login.password=Password@1234

# Login Details - Phone Number
userservice.qa.phone.login.identifier=phonenumberlogin
userservice.qa.phone.login.password=PASSword##11
userservice.qa.phone.code=+91

# Login Details - Username
userservice.qa.username.login.identifier=phonenumberlogin
userservice.qa.username.login.password=PASSword##11

# Login Details - Email
userservice.qa.email.login.identifier=allrightsp_xwjxdyzhz9moip
userservice.qa.email.login.password=PASSword@@@123

# Invalid Login Details
userservice.qa.invalid.identifier=invaliduser
userservice.qa.invalid.password=wrongpassword

# Origin
ep.sg.origin=qa.elevate-shikshagraha.shikshalokam.org
ep.sl.origin=qa.elevate-shikshalokam.shikshalokam.org






# User APIs
userservice.read.user.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/user/read

userservice.profilebyid.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/user/profileById/

userservice.update.user.endpoint=https://qa.elevate-apis.shikshalokam.org/user/v1/user/update

userservice.user.id=1

userservice.internal.access.token=Fqn0m0HQ0gXydRtBCg5l

userservice.update.user.name=NEVIL
userservice.update.user.location=ap
userservice.update.user.about=This is test
userservice.update.user.image=https://cloudstorage.com/container/abc.png
userservice.update.user.state=67037c725fb1cfaa2c13839e
userservice.update.user.role=8
userservice.update.user.district=67f4e1933bad83b75d4958e3
userservice.update.user.block=67f4e2197bd713b75309c8b1
userservice.update.user.cluster=67f4e25a3bad83b75d4958e7
userservice.update.user.school=67f4e2fa3bad83b75d4958ef
userservice.update.user.professional.role=67f4e2fa3bad83b75d4958ef
userservice.update.user.professional.subrole=67f4e2fa3bad83b75d4958ef